### ISSUE TITLE
pixel offsets

### ISSUE THREAD

**Issue by varna9000** [boochow/MicroPython-ST7735#1]
Hi, could you please patch the driver to allow screen x and y offset? I got a display which leaves some artefacts because of wrong (possibly ) memory mapping. Thank you.

**Comment by boochow** [comment]
Hi @varna9000 , if your display had a plastic film with green or blue tab, please try modifying  `graphicstest.py` to replace initr() at line 8 with initg() or initb()

**Comment by varna9000** [comment]
Hi @boochow, I don't remember what the tab colour was. I did replaced the functions on line 8, but with initr() and initg() I get the random pixel lines. With initb() the display is not working at all (except for the backlight). Any ideas why "b" is not working? I suspect my screen is blue tab.

**Comment by boochow** [comment]
You mentioned "some artifacts".
Is it like a set of garbage pixels seen in this picture?
https://blog.boochow.com/wp-content/uploads/arduino08-03.jpg

**Comment by varna9000** [comment]
@boochow yes, this is what I'm getting exactly! Do you know how to make an offset as it seems the whole display area is shifted with 1 or 2 pixels.

**Comment by boochow** [comment]
@varna9000 basically, adding offset values to parameters of _setwindowpoint() and _setwindowloc() makes it work. I added some lines and initb2() method to add (+2, +1) offset. Please try this new version.
( You need to modify line 8 of graphicstest.py  to call initb2() method. )

**Comment by varna9000** [comment]
Works perfectly. Thank you!
