### ISSUE TITLE
Framebuffer support

### ISSUE THREAD

**Issue by GHPS** [boochow/MicroPython-ST7735#3]
Thanks for this great library!

I'm using this library to display some terminal text on the
small TFT display. Unfortunately the speed for printing
text is rather low. Therefore updating the whole text
screen takes several seconds.

I tried solving this problem by implementing the
hardware scroll features of the chip (functions 0x33
and 0x37) but these function don't provide a real
scroll functionality but a vertical shift of the screen
content. The data of the screen buffer remain
unchanged.

For me the core problem is less the slow text()
function - it's rather charming to see the text
appear on the screen character by character.
It's the problem that I can't move parts of the
screen around, i.e. fast copy the screen buffer. 

Here the use of the framebuffer would
help imensensly since the fill() function
is rather quick. Text() (more char()) would 
write to the framebuf allowing it to be shifted 
or moved at will. 

Plus: This would allow the use of  your 
fine FBConsole (1) on a screen larger
than OLED  as well.,,

So: Do you see a chance to implement
a framebuffer support for the ST7735?

1: https://github.com/boochow/FBConsole

**Comment by GHPS** [comment]
Thanks for the great news!

I'm looking forward to testing the new features.

Meanwhile I stumbled upon the fine font_to_py
utility by Peter Hinch[1] which allow to convert
standard fonts to MicroPython embedded fonts.
The format used by Hinch is not only highly efficient
but also very similar to GuyCarver's (and your) format.

So it might be worth checking this format out...

1: https://github.com/peterhinch/micropython-font-to-py

**Comment by boochow** [comment]
I posted ST7735fb.py, a wrapper class module for ST7735 and FBConsole,  on the repo of FBConsole.
ST7735 can be used for dupterm() now!

And thank you for the font converter info. I will try it.

**Comment by GHPS** [comment]
> I have updated char() function to make text drawing speed a bit faster, so please try this new version.

The improvement in speed is enormous: Previously it took roughly 5.8 seconds to fill the
screen with text. That is now down to under a second. Great!

Moreover I upgraded to MicroPython 1.11 and precompiled the code to mpy files. With these
changes it takes half a second to print a screen of text - or under a second to do a full
scroll up of existing text (i.e. erase the text and redraw it).

Now this library can be used to display simple terminal output without any problems.

A big thank you!

**Comment by vahithosan** [comment]
> 
Hi. I want use custom font with font_to_py and this library. But I cant undarstand. Do you share example? 

My code:

```
from ST7735 import TFT,TFTColor
from machine import SPI,Pin
import fiert22tr #created with font_to_py
import time
import math
import writer
import framebuf
from ST7735fb import TFTfb

spi = SPI(1, 10_000_000, sck=Pin(14), mosi=Pin(13), miso=Pin(12))
gc.collect()
tft=TFT(spi, 2, 4, 15)
tft.initb2()
tft.rotation(1)
tft.rgb(True)

fb = TFTfb(tft, fiert22tr)

```

when write this:
`fb.text("A",0,0,TFT.WHITE)`

```
Traceback (most recent call last):
  File "<stdin>", line 20, in <module>
  File "ST7735fb.py", line 40, in text
  File "ST7735.py", line 202, in char
TypeError: 'module' object isn't subscriptable
```

**Comment by boochow** [comment]
@vahithosan I have not used font_to_py, but it seems it is designed to be used with framebuf class.
Because ST7735 class is not compatible with framebuf class, I'm afraid you can't use font_to_py with it.
