### ISSUE TITLE
black on white text?

### ISSUE THREAD

**Issue by katkinsk** [boochow/MicroPython-ST7735#5]
When trying to use black text on white background, it shows up only as black rectangles. Is there a way to use black text?

**Comment by boochow** [comment]
It is the side-effect of the change I made to speed up displaying characters.
Probably you can use this older version.

https://github.com/boochow/MicroPython-ST7735/blob/bc4572e4fcd9a7392557880320c2f2fe6ce45b23/ST7735.py

**Comment by katkinsk** [comment]
This works! Thank you!
